spring.application.name=bancassurance-payments-service
server.port=${SERVER_PORT:8085}
spring.profiles.active=${ACTIVE_PROFILE:develop}
server.servlet.context-path=${SERVER_CONTEXT_PATH:/api/v1/payments}

spring.datasource.url=jdbc:postgresql://${DATABASE_HOST:payments-db}:${DATABASE_PORT:5432}/${DATABASE_NAME:postgres}
spring.datasource.username=${DATABASE_USERNAME:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres123}

spring.jpa.hibernate.ddl-auto=${HIBERNATE_DDL:update}
spring.jpa.open-in-view=${JPA_OPEN_IN_VIEW:false}

# Kafka Configuration
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
app.config.kafka.topics.permissions=${KAFKA_TOPICS_PERMISSIONS:auth-permissions}
app.config.sync.permissions.enabled=${SYNC_PERMISSIONS_ENABLED:true}
