spring.application.name=bancassurance-payments-service
server.port=8005

spring.datasource.url=jdbc:postgresql://localhost:5432/bancassurance
spring.datasource.username=phijom
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
